sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.15.8
before_script:
  - npm prune
  # - npm run cover
  # - npm run lint
  # - npm run check-coverage
  - npm run build
after_success:
  # - npm run report-coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
